version: '3'

tasks:
  defaults:
    cmds:
      - task -a
    silent: true

  init:
    cmds:
      - npm install
    silent: true

  run:
    cmds:
      - npm run dev
    silent: true

  check:
    cmds:
      - npm run check

  build:
    cmds:
      - npm run build

  build-test:
    cmds:
      - docker build -t node-app-build -f docker/Dockerfile.build .
      - docker run --rm -it node-app-build