version: '3'

tasks:
  defaults:
    cmds:
      - task -a
    silent: true

  init:
    cmds:
      - npm install
    silent: true

  run:
    cmds:
      - npm run dev
    silent: true

  fix:
    cmds:
      - npm run fix